#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/bb96d929-cc55-41e5-8dba-4295a5bfb044

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String humiditySystem;
  float brightness;
  float humidity;
  float soilMoisture;
  float temperature;
  int luminositySystem;
  bool irrigationSystem;
  bool temperatureSystem;
  bool ventilationSystem;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

// ArduinoJson - Version: 6.16.1
#include <ArduinoJson.h>
#include <ArduinoJson.hpp>
#include "thingProperties.h"
#include "Connection.h"
#include "MsgServiceSerial.h"
#include "CloudParameterHolder.h"
#include "CloudActuatorSystemHolder.h"
#include "CloudVariableManager.h"
#include "MsgServiceArduino.h"
#include "Esp8266.h"
#include <stdio.h>
#include <string.h>


/* wifi network name */
#define SSIDNAME "wifi-network-name"
/* WPA2 PSK password */
#define PWD "wi-fi-password"
/* MQTT server */
#define MQTT_SERVER "broker.mqtt-dashboard.com"

#define INIT 0
#define RECEIVE 1
#define SEND 2

#define RX D6
#define TX D5

#define FREQ1 5000
#define FREQ2 20

#define GREENHOUSE_ID "greenhouse1"

MsgServiceArduino *msgARD;
Connection *conn;
CloudParameterHolder *parameterHolder;
CloudActuatorSystemHolder *actuatorHolder;
CloudVariableManager *cloudVariableManager;

int state;
int id;
int i = 0;
float termostatTemperature;
unsigned long previousMillis1 = 0;
unsigned long previousMillis2 = 0;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  termostatTemperature = temperature;
  
  msgARD = new MsgServiceArduino(RX, TX);
  msgARD->init();

  parameterHolder = new CloudParameterHolder(&brightness, &temperature, &humidity, &soilMoisture);
  actuatorHolder = new CloudActuatorSystemHolder(&luminositySystem, &temperatureSystem, &irrigationSystem, &ventilationSystem);

  cloudVariableManager = new CloudVariableManager(actuatorHolder, parameterHolder);

  conn = new Esp8266(SSIDNAME, PWD, MQTT_SERVER, msgARD, cloudVariableManager, GREENHOUSE_ID);
  conn->connecting();

  state = RECEIVE;

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {

  ArduinoCloud.update();
  conn->processIncomingMessages();
  if (msgARD->isMsgAvailable()) {
    Msg *message = msgARD->receiveMsg();
    String m = message->getContent();
    Serial.println(m);
    //invia dati con mqtt
    conn->sendData("dataSG", m);
    delete message;
  }
  delay(1000);


}

/*
  Since VentilationSystem is READ_WRITE variable, onVentilationSystemChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVentilationSystemChange()  {
  if(ventilationSystem)
  {
     msgARD->sendMsg(String("VENTILATION:on"));
  }else{
    msgARD->sendMsg(String("VENTILATION:off"));
  }
}

/*
  Since IrrigationSystem is READ_WRITE variable, onIrrigationSystemChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIrrigationSystemChange()  {
  if(irrigationSystem)
  {
     msgARD->sendMsg(String("IRRIGATION:on"));
  }else{
    msgARD->sendMsg(String("IRRIGATION:off"));
  }
}

/*
  Since TemperatureSystem is READ_WRITE variable, onTemperatureSystemChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureSystemChange()  {
  if(!temperatureSystem)
  {
     msgARD->sendMsg(String("TEMPERATURE:turn-off"));
  }
}

/*
  Since HumiditySystem is READ_WRITE variable, onHumiditySystemChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumiditySystemChange()  {
  if(humiditySystem)
  {
     msgARD->sendMsg(String("HUMIDITY:on"));
  }else{
    msgARD->sendMsg(String("HUMIDITY:off"));
  }
}

/*
  Since BrightnessSystem is READ_WRITE variable, onBrightnessSystemChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuminositySystemChange()  {
  String value = String(luminositySystem);
  msgARD->sendMsg(String("LUMINOSITY:" + value));
}

/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  if(temperatureSystem)
  {
    if(termostatTemperature < temperature)
    {
     msgARD->sendMsg(String("TEMPERATURE:increase"));
    }else if(termostatTemperature > temperature)
    {
      msgARD->sendMsg(String("TEMPERATURE:decrease"));
    }
  }
}